### ISSUE TITLE
can‘t specify multiple nodes (NodeosActionReader) 

### ISSUE THREAD

**Issue by learnergo** [EOSIO/demux-js#108]

**Comment by flux627** [comment]
Given the synchronous nature of demux, there would be little benefit to load balance across multiple nodes (if that's what you're looking for). If you're looking to select the "best node" (lowest latency, fastest response times) or distribute requests for rate limiting reasons, then I suggest you create a reverse proxy service that handles these things, exposing a single endpoint to Demux.
