### ISSUE TITLE
Error retrieving last irreversible block

### ISSUE THREAD

**Issue by iamonuwa** [EOSIO/demux-js#149]
I keep running into this error after setting up using the example code in the repo. I've tried 3 different api endpoints. But all return same error.

![image](https://user-images.githubusercontent.com/6551094/55541116-40a66d80-56bc-11e9-9bfc-9d95fd692811.png)

**Comment by flux627** [comment]
The endpoint was just updated to use `https://api.eosnewyork.io`. If this is still not working for you, make sure you can access this endpoint locally via [https://api.eosnewyork.io/v1/chain/get_info](https://api.eosnewyork.io/v1/chain/get_info). If you can access the endpoint but the example still does not work, feel free to re-open the issue with steps to reproduce.
