### ISSUE TITLE
Send email on action

### ISSUE THREAD

**Issue by bitcoiners** [EOSIO/demux-js#18]
Hello,
It would be nice to have an email sent on transfer to a selected account(s). 
If someone adds an example for this effect handler, it would be appreciated.

**Comment by flux627** [comment]
Basically, you would have an email provider (like Mailgun or Send Grid or Amazon SES) that you would call inside an Effect function that is subscribed to the action that you would like to trigger emails. Additionally, I would recommend you also submit a receipt transaction with the result of the email send, so you have some kind of record of the email being sent. You can use this receipt when replaying to decide if you need to send the email again or not.

A full example for this would be quite involved, and I think would be more appropriate in a separate repository. This may be the route we take for all new examples (and slightly unrelated, we may also move all class implementations into their own repositories).
