### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by k26dr** [EOSIO/demux-js#20]
We (Everipedia) are forking this repo to add MySQL support and plan on submitting a pull request. Before starting, we want to make sure someone at Block.one isn't already working on this. If they are, we'll stop our coding and wait on them to prevent conflicts.

**Comment by chris-allnutt** [comment]
@k26dr there are no current plans to implement a mySQL handler.

**Comment by flux627** [comment]
We look forward to reviewing your PR. Feel free to reach out if you need any guidance.

**Comment by k26dr** [comment]
Submitted PR #22 for this.

**Comment by k26dr** [comment]
Our Everipedia implementation using MySQL is available here: https://github.com/EveripediaNetwork/demux-sync. It's using a custom NPM package (demux-js-mysql) with MySQL support added. It's highly experimental, so no guarantees on performance, etc., but it's probably the best example out now for using the functionality if you have an urgent need for it.

**Comment by flux627** [comment]
See #32
