### ISSUE TITLE
bnet support for sync data

### ISSUE THREAD

**Issue by kesar** [EOSIO/demux-js#21]
Implement bnet protocol from nodeos in order to sync with blockchain.

Right now using http rpc endpoints will take too much time if you get out of sync.

As far as I know bnet is websockets protocol.

**Comment by chris-allnutt** [comment]
Please elaborate. This is very vague.

**Comment by kesar** [comment]
> Please elaborate. This is very vague.

Updated with a bit more of info 👍

**Comment by jeffreyssmith2nd** [comment]
There is a PR in the works that uses the nodeos MongoDB plugin rather than the http rpc endpoint which should help relieve load on the node/increase speed.
