### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ramtej** [EOSIO/demux-js#48]
Hello, 

I'm getting during the installation the following error: 

```
# Using yarn
yarn add demux

# Using npm
npm install demux --save
```

```
33 error Linux 4.15.0-33-generic
34 error argv "/usr/bin/node" "/usr/bin/npm" "install" "demux" "--save"
35 error node v8.10.0
36 error npm  v3.5.2
37 error code ENOSELF
38 error Refusing to install demux as a dependency of itself
39 error If you need help, you may report this error at:
39 error     <https://github.com/npm/npm/issues>
40 verbose exit [ 1, true ]
```

**Comment by flux627** [comment]
Are you trying to do this within the demux-js repo?

**Comment by flux627** [comment]
You also have a very old version of NPM.

**Comment by ramtej** [comment]
Hi, 
yes, I executed the 'npm install demux --save' within the repo. 

Ok, do you have any requirements, which nodejs is valid? I just installed the Ubuntu 18.04 package manager (apt) supported version.

**Comment by flux627** [comment]
You want to run that in your own NodeJS project, not this one. Check this out to get the most up to date NPM: 
https://nodejs.org/en/download/package-manager/

**Comment by ramtej** [comment]
ok, works now with the latest nodejs. thx!
