### ISSUE TITLE
something about actionType?

### ISSUE THREAD

**Issue by epochchaser** [EOSIO/demux-js#49]
Hi.
i need to intercept all the actions from actionType.
Official example writtend with eosio.token.
but i want to change to other contract.

something like
contract : eosiochaince
action : transfer

so i think => actionType : eosiochaince::transfer

but it is not working. what's wrong with this..?
thank you.

**Comment by flux627** [comment]
It is difficult to know what has gone wrong without actually seeing your code, can you post the relevant parts?

**Comment by epochchaser** [comment]
Hi.
I solved it with correct start block and BP.
