### ISSUE TITLE
how to query millions of rows from the smart contract multindex table ?

### ISSUE THREAD

**Issue by sivachaitanya** [EOSIO/demux-js#63]
i am building a dapp which stores millions of rows in the multindex table, how can I use demux to efficinetly query all the millions of rows quickly to feed to my analytics layer ? it would be great if you can point me to an example where demux can be used to query smart contract multindex rows ?

**Comment by chris-allnutt** [comment]
@sivachaitanya you can use demux-js with demux-js-postgres to store the data and query it there. Demux does not support direct querying of the contract table directly, it instead watches for actions and maintains it's own state in a database that can be queried with traditional SQL.

**Comment by sivachaitanya** [comment]
Thanks Chris, but what about the decentralization take of this process, where we store the data in a postgres database to perform rich queries instead directly pulling data from the blockchain ?
