### ISSUE TITLE
How can I get the data from the table which in the EOS smart contract? 

### ISSUE THREAD

**Issue by KevinHwangAi** [EOSIO/demux-js#72]
I am  trying to develop my DAPP by using demux. Now I need to get the data from my contract. How should demux be implemented?

**Comment by lachlangreenbank** [comment]
[EOS TRANSFER EXAMPLE]Check out https://github.com/EOSIO/demux-js/blob/develop/examples/eos-transfers/)

you can test it out by running it and deploying the eosio.token contract, it will catch the actions as they occur. Change the NODE its pointing at to your line 28 [index.js](https://github.com/EOSIO/demux-js/blob/develop/examples/eos-transfers/index.js).

https://github.com/EOSIO/demux-js/blob/develop/examples/eos-transfers/handlerVersions/v1/index.js

if you go down to line 71 and  49 Demux being told to watch ACCOUNT.ACTION. Replace these with your account name and action in the ABI file of your contracts. Edit updateTransferData() a bit too, incoming data the data is in the payload object.  That's pretty much the basics.

How you use/store the data is up to you in the effects and updater functions, i think there are Mongo and Postgres implementations for database storage.

**Comment by KevinHwangAi** [comment]
> [EOS TRANSFER EXAMPLE]Check out https://github.com/EOSIO/demux-js/blob/develop/examples/eos-transfers/)
> 
> you can test it out by running it and deploying the eosio.token contract, it will catch the actions as they occur. Change the NODE its pointing at to your line 28 [index.js](https://github.com/EOSIO/demux-js/blob/develop/examples/eos-transfers/index.js).
> 
> https://github.com/EOSIO/demux-js/blob/develop/examples/eos-transfers/handlerVersions/v1/index.js
> 
> if you go down to line 71 and 49 Demux being told to watch ACCOUNT.ACTION. Replace these with your account name and action in the ABI file of your contracts. Edit updateTransferData() a bit too, incoming data the data is in the payload object. That's pretty much the basics.
> 
> How you use/store the data is up to you in the effects and updater functions, i think there are Mongo and Postgres implementations for database storage.

Thanks for your help. But I need to call the data that has been saved on the chain in the multi-index table. Demux seems to have no  API for it?

**Comment by lachlangreenbank** [comment]
I don't think that is its intended function. No.

For getting the current state i use a RPC (https://github.com/EOSIO/demux-js/blob/develop/examples/eos-transfers/index.js)  call or a cleos shell command.

But this way can get tedious to maintain application data.

Demux can help alleviate having to check the chain state all the time by caching the state in a DB as is changes, making it easy to query.

**Comment by flux627** [comment]
This is a planned feature coming to EOSIO/demux-js-eos, but is currently on hold due to some changes needed to eosio and chainbase to help support it. If all goes well, we should be able to have a per-action diff for state changes (possibly even more granularly per-operation), which can be used in your updater functions.

Since this issue should be EOSIO/demux-js-eos, I'm closing this. Feel free to open another issue there.
