### ISSUE TITLE
How can I use demux in my test network?

### ISSUE THREAD

**Issue by wenji-my** [EOSIO/demux-js#77]
I change nodeosEndpoint into my test network endpoint,
````
const actionReader = new NodeosActionReader(
  "http://192.168.1.107:8888", 
  0,
)
````
but terminal didn't print anything when I complete a transition.

**Comment by lachlangreenbank** [comment]
If your URL is correct.

Are you sure your actions and contract name are correct?

Can i see your update and effect code?

**Comment by wenji-my** [comment]
@lachlangreenbank I'm using the examples eos-transfers. I just change the nodeosEndpoint from index.js. I don't know how to set up my contract. What api is used to set up the contract?

**Comment by lachlangreenbank** [comment]
You usually would use cleos to setup the contract.

make a wallet if you dont have one

cleos wallet create --name walletname --file walletname.txt

cleos create key  (do this twice)

cleos wallet import 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 (add both keys from above command that look like this key, write them down on a file too)

cleos create account eosio eosio.token <Owner Public Key> <Active Public Key>

and deploy contract with:

go to the folder build/contracts/eosio.token

cleos set contract eosio.token ./eosio.token.wasm ./eosio.token.abi

this guide is slightly out of date but helped me to understand, and covers a lot of the precursors / setup process on a VM : 
https://github.com/nsjames/Scatter-Tutorials/blob/master/setup.md 
https://www.youtube.com/watch?v=glB6UPHo1rA

to see the latest version of the API calls above check out : https://developers.eos.io/eosio-cleos/reference

**Comment by wenji-my** [comment]
@lachlangreenbank I already created a smart contract in test network. I mean that how to use demux to setup contract in project.

**Comment by lachlangreenbank** [comment]
Look at line 50 index.ts, that's where the contract and action to look for are defined, look through the rest of the code and adapt it to store the state of your contract rather than token.

**Comment by wenji-my** [comment]
@lachlangreenbank  It received the transfer data when I change it. Thank you!
