### ISSUE TITLE
The program stops automatically and no error is reported

### ISSUE THREAD

**Issue by learnergo** [EOSIO/demux-js#96]
And after I restart the program,it works fine.But after a few hours the problem arose again.

```
const rawBlock = yield this.httpRequest('post', {
            url: `${this.nodeosEndpoint}/v1/chain/get_block`,
            json: {block_num_or_id: blockNumber},
          })
```

no timeout ??

---------------------
demux version: 

"demux": "^3.0.0",
"demux-eos": "2.0.0",

**Comment by jeffreyssmith2nd** [comment]
Try upgrading to demux-eos 3.0.0, retries were added in that version.

**Comment by learnergo** [comment]
npm ERR! notarget No matching version found for demux-eos@3.0.0

And demux-eos@2.0.0 supports retry. The issue I think was caused by lacking 'timeout'.

**Comment by learnergo** [comment]
solved by "timeout"

closed

**Comment by learnergo** [comment]
sorry,3.0.0 did not solve my problem.
The demux process stop but not exit.It doesn't get any block.
...

**Comment by learnergo** [comment]
This is a bug caused by [nextBlock](https://github.com/EOSIO/demux-js/blob/master/src/AbstractActionReader.ts)
```
if (this.currentBlockNumber === this.headBlockNumber || !this.headBlockNumber) {
      this.headBlockNumber = await this.getLatestNeededBlockNumber()
    }
```
'===' should be replaced by '>='
getLatestNeededBlockNumber's result may be less than headBlockNumber because of fork. If so the process will be dead cycle.
