### ISSUE TITLE
how to stop watching?

### ISSUE THREAD

**Issue by learnergo** [EOSIO/demux-js#98]
I use demux as a part of my project. I dont find the method to stop watching

**Comment by flux627** [comment]
In the near future we plan to expose an endpoint to:
- See demux status
- Stop/resume watching
- Initiate Replay

But for now, you will have to implement your own ActionWatcher that gives you this ability. Off the top of my head you might be able to implement this by wrapping the last line of `BaseActionWatcher.watch` with some kind of conditional:

```js
if ( ... ) {
  setTimeout(async () => await this.watch(false), waitTime)
}
```
